import { notFound } from "next/navigation";
import Link from "next/link";
import { requireOrgContext } from "@/lib/session";
import { getCustomerDetail } from "@/services/customers";
import { PrintButton } from "@/app/(print)/sales/[id]/print/PrintButton";

export default async function CustomerStatementPrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, orgId, orgName } = await requireOrgContext();

  const customer = await getCustomerDetail(supabase, orgId, id);
  if (!customer) notFound();

  const today = new Date().toISOString().slice(0, 10);
  const overdue = customer.invoices.filter(
    (i) => i.total - i.amount_paid > 0 && i.due_date !== null && i.due_date < today
  );

  return (
    <div className="mx-auto max-w-3xl p-8 print:p-0">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <Link href={`/customers/${customer.id}`} className="text-sm text-slate-500 hover:underline">
          Back to customer
        </Link>
        <PrintButton />
      </div>

      <div className="border border-slate-200 p-8">
        <div className="flex items-start justify-between border-b-2 border-slate-800 pb-6">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">{orgName}</h1>
            <p className="mt-1 text-sm text-slate-500">Statement of Account</p>
          </div>
          <div className="text-right text-sm">
            <p className="font-medium text-slate-900">{customer.name}</p>
            <p className="text-slate-500">{customer.email ?? ""}</p>
            <p className="text-slate-500">As at {new Date().toLocaleDateString()}</p>
          </div>
        </div>

        <div className="mt-6 grid grid-cols-4 gap-4 text-center text-sm">
          <div className="rounded border border-slate-200 p-3">
            <p className="text-xs uppercase tracking-wide text-slate-400">Total billed</p>
            <p className="mt-1 font-semibold text-slate-900">${customer.totalBilled.toFixed(2)}</p>
          </div>
          <div className="rounded border border-slate-200 p-3">
            <p className="text-xs uppercase tracking-wide text-slate-400">Total paid</p>
            <p className="mt-1 font-semibold text-slate-900">${customer.totalPaid.toFixed(2)}</p>
          </div>
          <div className="rounded border border-slate-200 p-3">
            <p className="text-xs uppercase tracking-wide text-slate-400">Open balance</p>
            <p className="mt-1 font-semibold text-slate-900">${customer.openBalance.toFixed(2)}</p>
          </div>
          <div className="rounded border border-slate-200 p-3">
            <p className="text-xs uppercase tracking-wide text-slate-400">Overdue</p>
            <p className="mt-1 font-semibold text-danger-600">${customer.overdueBalance.toFixed(2)}</p>
          </div>
        </div>

        <table className="mt-8 w-full text-sm">
          <thead>
            <tr className="border-b border-slate-800 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">
              <th className="py-2">Invoice</th>
              <th className="py-2">Issued</th>
              <th className="py-2">Due</th>
              <th className="py-2 text-right">Total</th>
              <th className="py-2 text-right">Paid</th>
              <th className="py-2 text-right">Balance</th>
            </tr>
          </thead>
          <tbody>
            {customer.invoices.map((inv) => {
              const balance = inv.total - inv.amount_paid;
              const isOverdue = balance > 0 && inv.due_date !== null && inv.due_date < today;
              return (
                <tr key={inv.id} className="border-b border-slate-100">
                  <td className="py-2.5 font-medium">{inv.invoice_number}</td>
                  <td className="py-2.5">{new Date(inv.created_at).toLocaleDateString()}</td>
                  <td className={`py-2.5 ${isOverdue ? "font-semibold text-danger-600" : ""}`}>
                    {inv.due_date ? new Date(inv.due_date).toLocaleDateString() : "—"}
                    {isOverdue ? " (overdue)" : ""}
                  </td>
                  <td className="py-2.5 text-right">${inv.total.toFixed(2)}</td>
                  <td className="py-2.5 text-right">${inv.amount_paid.toFixed(2)}</td>
                  <td className="py-2.5 text-right font-medium">${balance.toFixed(2)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>

        {overdue.length > 0 && (
          <p className="mt-6 text-sm font-medium text-danger-600">
            {overdue.length} invoice{overdue.length === 1 ? " is" : "s are"} past due. Please arrange settlement.
          </p>
        )}

        <p className="mt-10 border-t border-slate-200 pt-4 text-center text-xs text-slate-400">
          Generated by {orgName} · USD
        </p>
      </div>
    </div>
  );
}
