import { notFound } from "next/navigation";
import Link from "next/link";
import { requireOrgContext } from "@/lib/session";
import { getTransferDetail } from "@/services/warehousing";
import { PrintButton } from "@/app/(print)/sales/[id]/print/PrintButton";

const statusLabel: Record<string, string> = {
  pending: "PENDING",
  in_transit: "IN TRANSIT",
  received: "RECEIVED",
  cancelled: "CANCELLED",
};

export default async function TransferNotePrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, orgId, orgName } = await requireOrgContext();

  const transfer = await getTransferDetail(supabase, orgId, id);
  if (!transfer) notFound();

  return (
    <div className="mx-auto max-w-3xl p-8 print:p-0">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <Link href="/warehousing" className="text-sm text-slate-500 hover:underline">
          Back to warehousing
        </Link>
        <PrintButton />
      </div>

      <div className="border border-slate-200 p-8">
        <div className="flex items-start justify-between border-b-2 border-slate-800 pb-6">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">{orgName}</h1>
            <p className="mt-1 text-sm text-slate-500">Stock Transfer Note</p>
          </div>
          <div className="text-right">
            <p className="text-xl font-semibold text-slate-900">{transfer.transfer_number}</p>
            <p className="mt-1 inline-block rounded border border-slate-300 px-2 py-0.5 text-xs font-semibold tracking-wide text-slate-600">
              {statusLabel[transfer.status] ?? transfer.status.toUpperCase()}
            </p>
          </div>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-6 text-sm">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">From warehouse</p>
            <p className="mt-1 font-medium text-slate-900">{transfer.fromName}</p>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">To warehouse</p>
            <p className="mt-1 font-medium text-slate-900">{transfer.toName}</p>
          </div>
        </div>
        <div className="mt-3 text-sm">
          <span className="text-slate-500">Transfer date: </span>
          <span className="font-medium">{new Date(transfer.transfer_date).toLocaleDateString()}</span>
        </div>

        <table className="mt-8 w-full text-sm">
          <thead>
            <tr className="border-b border-slate-800 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">
              <th className="py-2">SKU</th>
              <th className="py-2">Product</th>
              <th className="py-2 text-right">Qty</th>
              <th className="py-2 text-right">Received</th>
            </tr>
          </thead>
          <tbody>
            {transfer.lines.map((line) => (
              <tr key={line.id} className="border-b border-slate-100">
                <td className="py-2.5 font-mono text-xs">{line.sku || "—"}</td>
                <td className="py-2.5">{line.productName}</td>
                <td className="py-2.5 text-right">{line.quantity}</td>
                <td className="py-2.5 text-right text-slate-400">☐</td>
              </tr>
            ))}
          </tbody>
        </table>

        {transfer.notes && (
          <div className="mt-6">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Notes</p>
            <p className="mt-1 whitespace-pre-line text-sm text-slate-600">{transfer.notes}</p>
          </div>
        )}

        <div className="mt-12 grid grid-cols-3 gap-8 text-sm">
          <div className="border-t border-slate-300 pt-2">
            <p className="text-xs text-slate-400">Dispatched by</p>
          </div>
          <div className="border-t border-slate-300 pt-2">
            <p className="text-xs text-slate-400">Driver / carrier</p>
          </div>
          <div className="border-t border-slate-300 pt-2">
            <p className="text-xs text-slate-400">Received by</p>
          </div>
        </div>

        <p className="mt-10 border-t border-slate-200 pt-4 text-center text-xs text-slate-400">
          Generated by {orgName}
        </p>
      </div>
    </div>
  );
}
