import { notFound } from "next/navigation";
import Link from "next/link";
import { requireOrgContext } from "@/lib/session";
import { getInvoiceDetail } from "@/services/sales";
import { PrintButton } from "@/app/(print)/sales/[id]/print/PrintButton";

const statusLabel: Record<string, string> = {
  draft: "DRAFT",
  applied: "APPLIED",
};

export default async function CreditNotePrintPage({
  params,
}: {
  params: Promise<{ id: string; cnId: string }>;
}) {
  const { id, cnId } = await params;
  const { supabase, orgId, orgName } = await requireOrgContext();

  const invoice = await getInvoiceDetail(supabase, orgId, id);
  if (!invoice) notFound();

  const cn = invoice.creditNotes.find((c) => c.id === cnId);
  if (!cn) notFound();

  const { data: items, error } = await supabase
    .from("sales_credit_note_items")
    .select("id, description, quantity, unit_price, line_total")
    .eq("credit_note_id", cnId)
    .order("created_at");
  if (error) throw error;
  const lines = (items ?? []) as Array<{ id: string; description: string; quantity: number; unit_price: number; line_total: number }>;

  return (
    <div className="mx-auto max-w-3xl p-8 print:p-0">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <Link href={`/sales/${invoice.id}`} className="text-sm text-slate-500 hover:underline">
          Back to invoice
        </Link>
        <PrintButton />
      </div>

      <div className="border border-slate-200 p-8">
        <div className="flex items-start justify-between border-b-2 border-slate-800 pb-6">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">{orgName}</h1>
            <p className="mt-1 text-sm text-slate-500">Credit Note</p>
          </div>
          <div className="text-right">
            <p className="text-xl font-semibold text-slate-900">{cn.credit_note_number}</p>
            <p className="mt-1 inline-block rounded border border-slate-300 px-2 py-0.5 text-xs font-semibold tracking-wide text-slate-600">
              {statusLabel[cn.status] ?? cn.status.toUpperCase()}
            </p>
          </div>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-6 text-sm">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Customer</p>
            <p className="mt-1 font-medium text-slate-900">{invoice.customerName ?? "Walk-in customer"}</p>
            <p className="mt-3 text-xs font-semibold uppercase tracking-wide text-slate-400">Against invoice</p>
            <p className="mt-1 font-medium text-slate-900">{invoice.invoice_number}</p>
          </div>
          <div className="text-right">
            <div className="flex justify-between">
              <span className="text-slate-500">Date</span>
              <span className="font-medium">{new Date(cn.created_at).toLocaleDateString()}</span>
            </div>
            {cn.reason && (
              <div className="mt-2">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Reason</p>
                <p className="font-medium">{cn.reason}</p>
              </div>
            )}
          </div>
        </div>

        <table className="mt-8 w-full text-sm">
          <thead>
            <tr className="border-b border-slate-800 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">
              <th className="py-2">Description</th>
              <th className="py-2 text-right">Qty</th>
              <th className="py-2 text-right">Unit price</th>
              <th className="py-2 text-right">Amount</th>
            </tr>
          </thead>
          <tbody>
            {lines.map((item) => (
              <tr key={item.id} className="border-b border-slate-100">
                <td className="py-2.5">{item.description}</td>
                <td className="py-2.5 text-right">{item.quantity}</td>
                <td className="py-2.5 text-right">${item.unit_price.toFixed(2)}</td>
                <td className="py-2.5 text-right">${item.line_total.toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="mt-4 flex justify-end">
          <div className="w-64 text-sm">
            <div className="flex justify-between border-t border-slate-800 py-1.5 text-base font-semibold">
              <span>Credit total</span>
              <span>-${cn.subtotal.toFixed(2)}</span>
            </div>
          </div>
        </div>

        <p className="mt-10 border-t border-slate-200 pt-4 text-center text-xs text-slate-400">
          Generated by {orgName} · {invoice.currency}
        </p>
      </div>
    </div>
  );
}
